#!/usr/bin/env python3
"""Generate exhaustive Flyto2 Indexer references from implementation sources."""

from __future__ import annotations

import argparse
import ast
from collections import defaultdict
import json
from pathlib import Path
import re
import sys
from typing import Any

import yaml

ROOT = Path(__file__).resolve().parents[1]
REFERENCE = ROOT / "docs" / "reference"
HEADER = "<!-- Generated by scripts/generate-reference.py; do not edit. -->\n\n"


def code(value: Any) -> str:
    return str(value).replace("|", "\\|").replace("[", "&#91;").replace("]", "&#93;")


def clean(value: Any, limit: int = 220) -> str:
    text = " ".join(str(value or "").split())
    return text if len(text) <= limit else text[: limit - 3] + "..."


def relative(path: Path) -> str:
    return path.relative_to(ROOT).as_posix()


def source_link(path: Path, line: int) -> str:
    rel = relative(path)
    url_path = rel.replace("@", "%40")
    return f"[`{rel}:{line}`](https://github.com/flytohub/flyto-indexer/blob/main/{url_path}#L{line})"


def parse(path: Path) -> ast.Module:
    return ast.parse(path.read_text(encoding="utf-8"), filename=str(path))


def literal(node: ast.AST | None, default: Any = "") -> Any:
    if node is None:
        return default
    try:
        return ast.literal_eval(node)
    except (ValueError, TypeError):
        try:
            return ast.unparse(node)
        except Exception:
            return default


def summary(node: ast.AST) -> str:
    doc = ast.get_docstring(node, clean=True) if isinstance(node, (ast.Module, ast.ClassDef, ast.FunctionDef, ast.AsyncFunctionDef)) else None
    if not doc:
        return "The declaration and linked implementation are authoritative."
    first = re.split(r"(?<=[.!?])\s+|\n\s*\n", doc.strip(), maxsplit=1)[0]
    return clean(first)


def callable_signature(node: ast.FunctionDef | ast.AsyncFunctionDef) -> str:
    prefix = "async def" if isinstance(node, ast.AsyncFunctionDef) else "def"
    returns = f" -> {ast.unparse(node.returns)}" if node.returns else ""
    return f"{prefix} {node.name}({ast.unparse(node.args)}){returns}"


def source_files() -> list[Path]:
    roots = [ROOT / "src", ROOT / "scripts", ROOT / "examples", ROOT / "benchmarks"]
    files = [path for base in roots for path in base.rglob("*.py")]
    files.extend(path for path in (ROOT / "analyze.py", ROOT / "benchmark.py", ROOT / "index_all.py") if path.exists())
    return sorted(set(files))


def declarations(tree: ast.Module) -> list[tuple[int, str, str, str]]:
    rows: list[tuple[int, str, str, str]] = []

    def visit(nodes: list[ast.stmt], owner: str = "") -> None:
        for node in nodes:
            if isinstance(node, ast.ClassDef):
                bases = ", ".join(ast.unparse(base) for base in node.bases)
                signature = f"class {node.name}({bases})" if bases else f"class {node.name}"
                qualified = f"{owner}.{node.name}" if owner else node.name
                rows.append((node.lineno, "class", signature, summary(node)))
                visit(node.body, qualified)
            elif isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
                kind = "method" if owner and owner.split(".")[-1][:1].isupper() else "function"
                qualified = f"{owner}.{node.name}" if owner else node.name
                rows.append(
                    (
                        node.lineno,
                        kind,
                        callable_signature(node).replace(f" {node.name}(", f" {qualified}(", 1),
                        summary(node),
                    )
                )
                visit(node.body, qualified)

    visit(tree.body)
    return sorted(rows)


def modules_reference() -> str:
    rows = []
    total_lines = 0
    total_declarations = 0
    for path in source_files():
        text = path.read_text(encoding="utf-8", errors="ignore")
        tree = parse(path)
        count = len(declarations(tree))
        lines = len(text.splitlines())
        imports = sorted(
            {
                node.module.split(".")[0]
                for node in ast.walk(tree)
                if isinstance(node, ast.ImportFrom) and node.module
            }
            | {
                alias.name.split(".")[0]
                for node in ast.walk(tree)
                if isinstance(node, ast.Import)
                for alias in node.names
            }
        )
        rows.append((path, lines, count, ", ".join(imports[:12]) or "none", summary(tree)))
        total_lines += lines
        total_declarations += count

    out = [HEADER, "# Module Inventory\n\n"]
    out.append(
        f"Generated inventory: **{len(rows)} Python modules**, **{total_lines:,} lines**, "
        f"and **{total_declarations:,} class/function/method declarations**.\n\n"
    )
    out.append("| Module | Lines | Declarations | Direct import roots | Responsibility |\n|---|---:|---:|---|---|\n")
    for path, lines, count, imports, purpose in rows:
        out.append(f"| {source_link(path, 1)} | {lines} | {count} | `{code(imports)}` | {purpose} |\n")
    return "".join(out)


def python_reference() -> str:
    groups: dict[str, list[tuple[int, str, str, str]]] = {}
    for path in source_files():
        rows = declarations(parse(path))
        if rows:
            groups[relative(path)] = rows
    total = sum(len(rows) for rows in groups.values())
    out = [HEADER, "# Python API Reference\n\n"]
    out.append(
        "Every declared class, function, nested function, and method in the package, support scripts, examples, benchmarks, and root command entry scripts. "
        f"Generated inventory: **{total:,} declarations across {len(groups)} files**.\n\n"
    )
    for rel, rows in groups.items():
        path = ROOT / rel
        out.append(f"## `{rel}`\n\n| Kind | Signature | Responsibility | Source |\n|---|---|---|---|\n")
        for line, kind, signature, purpose in rows:
            out.append(f"| {kind} | `{code(signature)}` | {purpose} | {source_link(path, line)} |\n")
        out.append("\n")
    return "".join(out)


def keyword_map(call: ast.Call) -> dict[str, Any]:
    return {item.arg: literal(item.value) for item in call.keywords if item.arg}


def cli_reference() -> str:
    path = ROOT / "src" / "cli.py"
    parser_paths = [path, ROOT / "src" / "task_cli.py"]
    trees = {parser_path: parse(parser_path) for parser_path in parser_paths}
    commands: dict[str, dict[str, Any]] = {}
    arguments: dict[str, list[dict[str, Any]]] = defaultdict(list)

    for parser_path, parser_tree in trees.items():
        parser_vars: dict[str, str] = {}
        for node in ast.walk(parser_tree):
            if not isinstance(node, ast.Assign) or not isinstance(node.value, ast.Call):
                continue
            call = node.value
            if not isinstance(call.func, ast.Attribute) or call.func.attr != "add_parser" or not call.args:
                continue
            name = literal(call.args[0])
            if not isinstance(name, str):
                continue
            variable = next((target.id for target in node.targets if isinstance(target, ast.Name)), "")
            metadata = keyword_map(call)
            commands[name] = {
                "variable": variable,
                "help": metadata.get("help", ""),
                "description": metadata.get("description", ""),
                "line": node.lineno,
                "path": parser_path,
                "handler": "",
            }
            parser_vars[variable] = name

        for node in ast.walk(parser_tree):
            if not isinstance(node, ast.Call) or not isinstance(node.func, ast.Attribute):
                continue
            if node.func.attr != "add_argument" or not isinstance(node.func.value, ast.Name):
                continue
            command = parser_vars.get(node.func.value.id)
            if not command:
                continue
            metadata = keyword_map(node)
            flags = [literal(item) for item in node.args]
            arguments[command].append(
                {
                    "flags": ", ".join(str(item) for item in flags),
                    "required": metadata.get("required", False),
                    "default": metadata.get("default", "required" if not any(str(item).startswith("-") for item in flags) else ""),
                    "choices": metadata.get("choices", ""),
                    "help": metadata.get("help", ""),
                    "line": node.lineno,
                    "path": parser_path,
                }
            )

    for node in ast.walk(trees[path]):
        if not isinstance(node, ast.If) or not isinstance(node.test, ast.Compare):
            continue
        comparison = node.test
        if len(comparison.comparators) != 1:
            continue
        command = literal(comparison.comparators[0])
        if not isinstance(command, str) or command not in commands:
            continue
        assignment = next(
            (
                item
                for item in node.body
                if isinstance(item, ast.Assign)
                and isinstance(item.value, ast.Call)
                and isinstance(item.value.func, ast.Name)
                and item.value.func.id.startswith("cmd_")
            ),
            None,
        )
        if assignment:
            commands[command]["handler"] = assignment.value.func.id

    out = [HEADER, "# CLI Command Reference\n\n"]
    out.append(
        f"The `flyto-index` argparse surface contains **{len(commands)} subcommands** and "
        f"**{sum(len(items) for items in arguments.values())} command arguments**.\n\n"
    )
    for name, metadata in commands.items():
        out.append(f"## `flyto-index {name}`\n\n")
        out.append(f"{clean(metadata['description'] or metadata['help'])}\n\n")
        out.append(f"Handler: `{metadata['handler'] or 'inline dispatch'}`. Source: {source_link(metadata['path'], metadata['line'])}.\n\n")
        out.append("| Argument | Required | Default | Choices | Purpose | Source |\n|---|---|---|---|---|---|\n")
        for item in arguments[name]:
            choices = ", ".join(map(str, item["choices"])) if isinstance(item["choices"], (list, tuple)) else item["choices"]
            out.append(
                f"| `{code(item['flags'])}` | {'yes' if item['required'] else 'no'} | `{code(item['default'])}` | "
                f"`{code(choices)}` | {clean(item['help'])} | {source_link(item['path'], item['line'])} |\n"
            )
        out.append("\n")
    return "".join(out)


def tool_definitions(path: Path, variable: str) -> list[dict[str, Any]]:
    tree = parse(path)
    tools: list[dict[str, Any]] = []
    for node in tree.body:
        assignment_value: ast.AST | None = None
        if isinstance(node, ast.Assign) and any(
            isinstance(target, ast.Name) and target.id == variable for target in node.targets
        ):
            assignment_value = node.value
        elif isinstance(node, ast.AnnAssign) and isinstance(node.target, ast.Name) and node.target.id == variable:
            assignment_value = node.value

        if assignment_value is not None:
            value = literal(assignment_value, [])
            if isinstance(value, list):
                for item, source_node in zip(value, assignment_value.elts, strict=True):
                    if isinstance(item, dict):
                        tools.append({**item, "_line": source_node.lineno})
        elif (
            isinstance(node, ast.Expr)
            and isinstance(node.value, ast.Call)
            and isinstance(node.value.func, ast.Attribute)
            and isinstance(node.value.func.value, ast.Name)
            and node.value.func.value.id == variable
            and node.value.func.attr == "append"
            and node.value.args
        ):
            value = literal(node.value.args[0], {})
            if isinstance(value, dict):
                tools.append({**value, "_line": node.lineno})
    return tools


def mcp_reference() -> str:
    granular_path = ROOT / "src" / "tool_registry" / "mcp_tools.py"
    smart_path = ROOT / "src" / "tool_registry" / "smart_tools.py"
    smart = tool_definitions(smart_path, "SMART_TOOLS")
    granular = tool_definitions(granular_path, "MCP_TOOLS")
    out = [HEADER, "# MCP Tool Reference\n\n"]
    out.append(
        f"The stdio server publishes **{len(smart)} smart tools**. The registry retains "
        f"**{len(granular)} granular compatibility definitions** for dispatch, integrations, and schema generation.\n\n"
    )
    for heading, tools, path in (("Published smart tools", smart, smart_path), ("Granular compatibility tools", granular, granular_path)):
        out.append(f"## {heading}\n\n")
        for tool in tools:
            schema = tool.get("inputSchema", {})
            properties = schema.get("properties", {})
            required = set(schema.get("required", []))
            out.append(f"### `{tool.get('name', '')}`\n\n{clean(tool.get('description', ''), 500)}\n\n")
            annotations = ", ".join(f"{key}={str(value).lower()}" for key, value in tool.get("annotations", {}).items()) or "none"
            out.append(
                f"Annotations: `{annotations}`. Definition: "
                f"{source_link(path, int(tool.get('_line', 1)))}.\n\n"
            )
            if properties:
                out.append("| Input | Type | Required | Default / enum | Purpose |\n|---|---|---|---|---|\n")
                for name, definition in properties.items():
                    detail = definition.get("enum", definition.get("default", ""))
                    out.append(
                        f"| `{name}` | `{definition.get('type', 'any')}` | {'yes' if name in required else 'no'} | "
                        f"`{code(detail)}` | {clean(definition.get('description', ''))} |\n"
                    )
                out.append("\n")
    return "".join(out)


def http_reference() -> str:
    path = ROOT / "src" / "api_server.py"
    tree = parse(path)
    spec: dict[str, Any] = {}
    for node in tree.body:
        if isinstance(node, ast.Assign) and any(isinstance(target, ast.Name) and target.id == "OPENAPI_SPEC" for target in node.targets):
            value = literal(node.value, {})
            if isinstance(value, dict):
                spec = value
            break
    rows = []
    for endpoint, operations in spec.get("paths", {}).items():
        for method, operation in operations.items():
            if method.lower() not in {"get", "post", "put", "patch", "delete"}:
                continue
            rows.append((method.upper(), endpoint, operation.get("operationId", ""), operation.get("summary", ""), operation.get("description", "")))
    out = [HEADER, "# Local HTTP API Reference\n\n"]
    out.append(
        f"The optional localhost bridge exposes **{len(rows)} OpenAPI operations**. It is separate from the default MCP stdio transport.\n\n"
    )
    out.append("| Method | Path | Operation | Summary | Contract source |\n|---|---|---|---|---|\n")
    for method, endpoint, operation, title, description in rows:
        out.append(f"| `{method}` | `{endpoint}` | `{operation}` | {clean(description or title)} | {source_link(path, 1)} |\n")
    return "".join(out)


def flatten_yaml(value: Any, prefix: str = "") -> list[tuple[str, Any]]:
    rows: list[tuple[str, Any]] = []
    if isinstance(value, dict):
        for key, child in value.items():
            path = f"{prefix}.{key}" if prefix else str(key)
            if isinstance(child, dict):
                rows.extend(flatten_yaml(child, path))
            else:
                rows.append((path, child))
    return rows


def configuration_reference() -> str:
    default_path = ROOT / "config" / "default.yaml"
    defaults = yaml.safe_load(default_path.read_text(encoding="utf-8")) or {}
    env: dict[str, set[str]] = defaultdict(set)
    patterns = (
        re.compile(r"os\.environ\.get\([\"']([A-Z][A-Z0-9_]+)"),
        re.compile(r"os\.getenv\([\"']([A-Z][A-Z0-9_]+)"),
        re.compile(r"os\.environ\[[\"']([A-Z][A-Z0-9_]+)"),
    )
    for path in [*source_files(), *sorted((ROOT / "scripts").glob("*.py"))]:
        text = path.read_text(encoding="utf-8", errors="ignore")
        for pattern in patterns:
            for match in pattern.finditer(text):
                env[match.group(1)].add(relative(path))

    rules = []
    for path in sorted((ROOT / "config" / "rules").glob("*.yaml")):
        data = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
        rules.append((path, ", ".join(data.keys()), len(flatten_yaml(data))))

    out = [HEADER, "# Configuration Reference\n\n"]
    out.append("## Default scanner configuration\n\n| Key | Default | Source |\n|---|---|---|\n")
    for key, value in flatten_yaml(defaults):
        out.append(f"| `{key}` | `{code(json.dumps(value, ensure_ascii=False))}` | {source_link(default_path, 1)} |\n")
    out.append(f"\n## Environment variables ({len(env)})\n\n| Variable | Readers |\n|---|---|\n")
    for name, owners in sorted(env.items()):
        out.append(f"| `{name}` | {', '.join(f'`{owner}`' for owner in sorted(owners))} |\n")
    out.append(f"\n## Built-in rule corpus ({len(rules)} files)\n\n| File | Top-level sections | Leaf contracts |\n|---|---|---:|\n")
    for path, sections, leaves in rules:
        out.append(f"| {source_link(path, 1)} | `{sections}` | {leaves} |\n")
    return "".join(out)


def index_reference() -> str:
    return HEADER + """# Generated Reference

- [Module inventory](modules.md): every non-test Python module, responsibility, size, import roots, and declaration count.
- [Python API](python-api.md): every non-test class, function, nested function, and method signature.
- [CLI commands](cli.md): every `flyto-index` subcommand and argument.
- [MCP tools](mcp-tools.md): all published smart tools and granular compatibility definitions.
- [Local HTTP API](http-api.md): every operation in the built-in OpenAPI contract.
- [Configuration](configuration.md): defaults, environment variables, and built-in rule corpus.

Run `python3 scripts/generate-reference.py` after changing a documented source.
CI executes the same command with `--check` and rejects drift.
"""


def outputs() -> dict[Path, str]:
    documents = {
        REFERENCE / "README.md": index_reference(),
        REFERENCE / "modules.md": modules_reference(),
        REFERENCE / "python-api.md": python_reference(),
        REFERENCE / "cli.md": cli_reference(),
        REFERENCE / "mcp-tools.md": mcp_reference(),
        REFERENCE / "http-api.md": http_reference(),
        REFERENCE / "configuration.md": configuration_reference(),
    }
    return {path: content.rstrip() + "\n" for path, content in documents.items()}


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail when generated files are stale")
    args = parser.parse_args()
    stale: list[str] = []
    for path, content in outputs().items():
        if args.check:
            if not path.exists() or path.read_text(encoding="utf-8") != content:
                stale.append(relative(path))
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8")
    if stale:
        print("stale generated documentation:\n" + "\n".join(f"- {item}" for item in stale), file=sys.stderr)
        return 1
    print("generated documentation: PASS" if args.check else "generated documentation: updated")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
