"""Workspace lifecycle, setup, task, and tool-list CLI handlers."""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import sys
import time
from datetime import datetime, timezone
from pathlib import Path

from . import __version__
from .task_cli import (
    execute_task_command, execute_task_status, execute_usage_record,
    execute_usage_report, task_evidence_tool_descriptions,
)


HOOK_MARKER_BEGIN = "# --- flyto-indexer begin ---"

HOOK_MARKER_END = "# --- flyto-indexer end ---"

HOOK_CONTENT = """\
# --- flyto-indexer begin ---
# stdout is discarded too: scan prints a JSON report, and a post-commit hook
# that writes to stdout floods the terminal after every commit.
flyto-index scan . >/dev/null 2>&1 &
# --- flyto-indexer end ---
"""

CLAUDE_MARKER_BEGIN = "<!-- flyto-indexer begin -->"

CLAUDE_MARKER_END = "<!-- flyto-indexer end -->"

CLAUDE_SECTION = """\
<!-- flyto-indexer begin -->
## Code Intelligence (flyto-indexer)

This project is indexed by [flyto-indexer](https://pypi.org/project/flyto-indexer/). Use its MCP tools for code changes.

### First-time setup
If `.flyto-index/` does not exist in the project root, run this before using any flyto-indexer tools:
```bash
flyto-index scan .
```

### ALWAYS use flyto-indexer tools when:
- **Auditing or reviewing** a project → `audit`
- **Understanding code** → `search`, `structure`
- **Before modifying code** → `task(action='plan')` (call FIRST), then follow the `execution_plan`
- **Checking impact** → `impact(target='symbol_name')` or `impact(mode='unstaged')`
- **During modifications** → `task(action='gate')` at each phase gate before proceeding
- **After modifications** → `task(action='validate')` to run ruff + pytest
- **When analysis or guidance is wrong, slow, or incomplete** → `task(action='feedback')`

### Workflow for code changes
1. `task(action='plan')` — get risk dimensions, constraints, and execution plan
2. Follow `execution_plan` steps in order — each step has tool name and pre-filled args
3. `task(action='gate')` at gate steps — server-side enforcement blocks skipping gates
4. Respect `constraints.max_files_per_step`
5. `task(action='validate')` — run linter + tests after making changes
6. `task(action='feedback')` — record structured local evidence for future improvement

### Project Rules (`.flyto-rules.yaml`)

When the user corrects you (e.g., "don't put files there", "don't use that pattern"), do two things:
1. Fix the immediate issue
2. Write a verifiable rule so it's enforced permanently — use the flyto-indexer `add_rule` function or create/update `.flyto-rules.yaml` directly:

```yaml
# .flyto-rules.yaml
architecture:
  - rule: "description of the constraint"
    glob_deny: ["pattern/**/*.ext"]           # files that should not exist
    grep_deny: [{ pattern: 'regex', glob: "*.ext" }]  # code that should not appear
    source: "user feedback YYYY-MM-DD"

style:
  - rule: "style convention"
    grep_deny: [{ pattern: 'anti_pattern', glob: "*.ext" }]
    example: "correct usage"

conventions:
  - rule: "text-only guidance (no automated check)"
```

The `audit` tool checks these rules automatically. This ensures corrections are never repeated — by any AI, any tool.
<!-- flyto-indexer end -->
"""

CLAUDE_SETTINGS_PATH = Path.home() / ".claude" / "settings.json"

MCP_SERVER_KEY = "flyto-indexer"

def _ensure_gitignore(directory: Path):
    """Create .gitignore with '*' in a generated directory if it doesn't exist."""
    gi = directory / ".gitignore"
    if not gi.exists():
        gi.write_text("# Auto-generated by flyto-indexer — keep IDE and git from indexing this directory\n*\n")

def cmd_init(args):
    """Initialize .flyto/ in a project directory."""

    project_path = Path(args.path).resolve()
    project_name = args.name or project_path.name

    if not project_path.exists():
        print(f"Path does not exist: {project_path}", file=sys.stderr)
        sys.exit(1)

    flyto_dir = project_path / ".flyto"
    nav_dir = flyto_dir / "nav"
    index_dir = flyto_dir / "index"

    if flyto_dir.exists():
        print(f".flyto/ already exists at {flyto_dir}")
        print("Use 'flyto-index scan' to update the index.")
        return {"ok": True, "message": "already exists", "path": str(flyto_dir)}

    # Create minimal structure
    nav_dir.mkdir(parents=True, exist_ok=True)
    index_dir.mkdir(parents=True, exist_ok=True)
    _ensure_gitignore(flyto_dir)

    # Auto-exclude from IDE file watchers (WebStorm, VSCode, etc.)
    from .engine import _ensure_ide_exclude
    _ensure_ide_exclude(project_path)

    now = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")

    # Write flyto.json
    flyto_json = {
        "schemaVersion": 1,
        "generatedAt": now,
        "project": {"name": project_name, "root": "."},
        "generator": {"name": "flyto-indexer", "version": "0.2.0"},
        "paths": {
            "map": "nav/map.json",
            "descriptions": "descriptions.jsonl",
            "indexSummary": "index/summary.json",
        },
    }
    (flyto_dir / "flyto.json").write_text(
        json.dumps(flyto_json, indent=2, ensure_ascii=False) + "\n",
        encoding="utf-8",
    )

    # Write empty nav/map.json
    map_json = {
        "schemaVersion": 1,
        "generatedAt": now,
        "categories": [],
        "hotspots": [],
    }
    (nav_dir / "map.json").write_text(
        json.dumps(map_json, indent=2, ensure_ascii=False) + "\n",
        encoding="utf-8",
    )

    # Write empty descriptions.jsonl
    desc_path = flyto_dir / "descriptions.jsonl"
    if not desc_path.exists():
        desc_path.write_text("", encoding="utf-8")

    # Write empty index/summary.json
    summary_json = {
        "schemaVersion": 1,
        "generatedAt": now,
        "counts": {"files": 0, "folders": 0, "symbols": 0, "languages": {}},
        "stalenessHint": {"recommendedReindexAfterHours": 24},
    }
    (index_dir / "summary.json").write_text(
        json.dumps(summary_json, indent=2, ensure_ascii=False) + "\n",
        encoding="utf-8",
    )

    print(f"Initialized .flyto/ at {flyto_dir}")

    # Add to .gitignore
    if not args.no_gitignore:
        gitignore_path = project_path / ".gitignore"
        entries = [".flyto/", ".flyto-index/"]
        existing_lines = []
        if gitignore_path.exists():
            existing_lines = gitignore_path.read_text().splitlines()

        missing_entries = [entry for entry in entries if entry not in existing_lines]
        if missing_entries:
            with open(gitignore_path, "a") as f:
                if gitignore_path.exists() and not gitignore_path.read_text().endswith("\n"):
                    f.write("\n")
                f.write("\n# Flyto2 indexes (generated)\n")
                for entry in missing_entries:
                    f.write(f"{entry}\n")
            print(f"Added {', '.join(repr(e) for e in missing_entries)} to .gitignore")

    # Optionally run indexer
    if args.index:
        print("\nRunning indexer...")
        args_scan = argparse.Namespace(
            path=str(project_path), full=False, name=project_name, output=None
        )
        return cmd_scan(args_scan)

    return {"ok": True, "path": str(flyto_dir)}

def _status_from_modern_index(project_path: Path) -> dict | None:
    """Build status from the primary .flyto-index/index.json format."""
    index_dir = project_path / ".flyto-index"
    index_path = index_dir / "index.json"
    if not index_path.exists():
        return None

    data = json.loads(index_path.read_text(encoding="utf-8"))
    symbols = data.get("symbols", {})
    dependencies = data.get("dependencies", {})
    files = data.get("files", {})

    languages = {}
    for symbol in symbols.values():
        language = symbol.get("language") or "unknown"
        languages[language] = languages.get(language, 0) + 1

    content_records = 0
    content_path = index_dir / "content.jsonl"
    if content_path.exists():
        content = content_path.read_text(encoding="utf-8").strip()
        content_records = len(content.splitlines()) if content else 0

    return {
        "ok": True,
        "project": data.get("project", project_path.name),
        "schemaVersion": data.get("schemaVersion", 1),
        "generatedAt": data.get("indexed_at", ""),
        "generator": data.get("generator", {}).get("version", ""),
        "index_format": ".flyto-index",
        "index_dir": str(index_dir),
        "has_content_file": bool(data.get("has_content_file")),
        "content_records": content_records,
        "counts": {
            "files": len(files),
            "symbols": len(symbols),
            "dependencies": len(dependencies),
            "languages": languages,
        },
        "tags": {},
        "tags_total": 0,
        "descriptions": {"total": 0},
    }

def _status_from_legacy_flyto(project_path: Path) -> dict | None:
    """Build status from the legacy .flyto/ metadata format."""
    flyto_dir = project_path / ".flyto"
    if not flyto_dir.exists():
        return None

    flyto_json = {}
    flyto_path = flyto_dir / "flyto.json"
    if flyto_path.exists():
        flyto_json = json.loads(flyto_path.read_text(encoding="utf-8"))

    summary = {}
    summary_path = flyto_dir / "index" / "summary.json"
    if summary_path.exists():
        summary = json.loads(summary_path.read_text(encoding="utf-8"))

    tag_counts = {}
    tag_total = 0
    tags_path = flyto_dir / "tags" / "symbol_tags.jsonl"
    if tags_path.exists():
        for line in tags_path.read_text(encoding="utf-8").strip().split("\n"):
            if not line.strip():
                continue
            try:
                tag = json.loads(line)
                kind = tag.get("kind", "unknown")
                tag_counts[kind] = tag_counts.get(kind, 0) + 1
                tag_total += 1
            except json.JSONDecodeError:
                pass

    desc_count = 0
    desc_path = flyto_dir / "descriptions.jsonl"
    if desc_path.exists():
        content = desc_path.read_text(encoding="utf-8").strip()
        if content:
            desc_count = len(content.split("\n"))

    tag_stats = summary.get("tags", {})
    desc_stats = summary.get("descriptions", {})
    return {
        "ok": True,
        "project": flyto_json.get("project", {}).get("name", "unknown"),
        "schemaVersion": flyto_json.get("schemaVersion", 0),
        "generatedAt": flyto_json.get("generatedAt", ""),
        "generator": flyto_json.get("generator", {}).get("version", ""),
        "index_format": ".flyto",
        "index_dir": str(flyto_dir),
        "counts": summary.get("counts", {}),
        "tags": tag_stats if tag_stats else tag_counts,
        "tags_total": tag_total,
        "descriptions": desc_stats if desc_stats else {"total": desc_count},
    }

def cmd_status(args):
    """Show index status for a project."""
    project_path = Path(args.path).resolve()

    result = _status_from_modern_index(project_path) or _status_from_legacy_flyto(project_path)
    if not result:
        message = "no .flyto-index/ or .flyto/ found"
        if hasattr(args, "as_json") and args.as_json:
            return {"ok": False, "error": message}
        print(f"No .flyto-index/ or .flyto/ found at {project_path}")
        print("Run 'flyto-index scan <path>' to create .flyto-index/.")
        return {"ok": False, "error": message}

    if hasattr(args, "as_json") and args.as_json:
        return result

    counts = result.get("counts", {})
    tag_stats = result.get("tags", {})
    desc_stats = result.get("descriptions", {})

    print(f"Flyto2 Status: {result['project']}")
    print(f"  Format:     {result.get('index_format', 'unknown')}")
    print(f"  Index Dir:  {result.get('index_dir', '')}")
    print(f"  Schema:     v{result['schemaVersion']}")
    print(f"  Generated:  {result['generatedAt']}")
    print(f"  Generator:  flyto-indexer {result['generator']}")
    print()
    print(f"  Files:      {counts.get('files', 0)}")
    print(f"  Symbols:    {counts.get('symbols', 0)}")
    print(f"  Dependencies: {counts.get('dependencies', 0)}")
    print(f"  Languages:  {counts.get('languages', {})}")
    if result.get("has_content_file"):
        print(f"  Content:    {result.get('content_records', 0)} records")
    print()
    if tag_stats:
        print("  Tags:")
        print(f"    Dead code:      {tag_stats.get('dead_code', 0)} symbols ({tag_stats.get('dead_code_lines', 0)} lines)")
        print(f"    TDD covered:    {tag_stats.get('tdd_covered', 0)} / {tag_stats.get('tdd_testable', 0)} testable")
        print(f"    TDD uncovered:  {tag_stats.get('tdd_uncovered', 0)}")
    else:
        print("  Tags: (none)")
    print()
    if desc_stats and "fresh" in desc_stats:
        desc_total = desc_stats.get("total", 0)
        desc_fresh = desc_stats.get("fresh", 0)
        hs_total = desc_stats.get("hotspot_total", 0)
        hs_covered = desc_stats.get("hotspot_covered", 0)
        print(f"  Descriptions: {desc_fresh}/{desc_total} files covered")
        if hs_total > 0:
            print(f"    Hotspots:   {hs_covered}/{hs_total} covered")
    else:
        print(f"  Descriptions: {desc_stats.get('total', 0)} entries")

    return result

def cmd_scan(args):
    """Execute scan command"""
    from .engine import IndexEngine

    project_path = Path(args.path).resolve()
    project_name = args.name or project_path.name
    index_dir = Path(args.output) if args.output else None

    engine = IndexEngine(project_name, project_path, index_dir)
    result = engine.scan(incremental=not args.full)

    return result

def cmd_impact(args):
    """Execute impact command"""
    from .engine import IndexEngine

    project_path = Path(args.path).resolve()
    project_name = project_path.name

    engine = IndexEngine(project_name, project_path)
    result = engine.impact(args.symbol_id, args.depth)

    return result

def cmd_context(args):
    """Execute context command"""
    from .engine import IndexEngine

    project_path = Path(args.path).resolve()
    project_name = project_path.name

    engine = IndexEngine(project_name, project_path)
    result = engine.context(
        query=args.query,
        paths=args.files,
        symbols=args.symbols,
        level=args.level,
    )

    return result

def cmd_outline(args):
    """Execute outline command"""
    from .engine import IndexEngine

    project_path = Path(args.path).resolve()
    project_name = args.name or project_path.name

    engine = IndexEngine(project_name, project_path)
    return engine.outline()

def cmd_brief(args):
    """Generate or display .flyto/brief.md."""
    from .flyto_output import generate_brief_from_flyto

    project_path = Path(args.path).resolve()
    content = generate_brief_from_flyto(project_path)
    print(content)

def cmd_describe(args):
    """Read or write file descriptions in .flyto/descriptions.jsonl."""
    from datetime import datetime, timezone

    project_path = Path(args.path).resolve()
    flyto_dir = project_path / ".flyto"
    desc_path = flyto_dir / "descriptions.jsonl"

    if not flyto_dir.exists():
        print(f"No .flyto/ found at {project_path}", file=sys.stderr)
        print("Run 'flyto-index init' to initialize.", file=sys.stderr)
        sys.exit(1)

    file_path = args.file_path

    if args.summary:
        # Write mode: append/update description
        # Compute file hash if the file exists
        full_file_path = project_path / file_path
        file_hash = ""
        if full_file_path.exists():
            content = full_file_path.read_bytes()
            file_hash = hashlib.sha256(content).hexdigest()[:16]

        now = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
        entry = {
            "path": file_path,
            "hash": file_hash,
            "one_liner": args.summary,
            "source": args.source,
            "updatedAt": now,
        }
        line = json.dumps(entry, ensure_ascii=False)

        # Append to descriptions.jsonl
        with open(desc_path, "a", encoding="utf-8") as f:
            if desc_path.exists() and desc_path.stat().st_size > 0:
                # Check if file ends with newline
                with open(desc_path, "rb") as check:
                    check.seek(-1, 2)
                    if check.read(1) != b"\n":
                        f.write("\n")
            f.write(line + "\n")

        print(f"Updated: {file_path}")
        print(f"  {args.summary}")

    else:
        # Read mode: find latest description for this file
        if not desc_path.exists():
            print("No descriptions found. Run 'flyto-index scan' first.", file=sys.stderr)
            sys.exit(1)

        latest = None
        for line in desc_path.read_text(encoding="utf-8").strip().split("\n"):
            if not line.strip():
                continue
            try:
                entry = json.loads(line)
                if entry.get("path") == file_path:
                    latest = entry
            except json.JSONDecodeError:
                pass

        if latest:
            # Check staleness
            full_file_path = project_path / file_path
            stale = False
            if full_file_path.exists() and latest.get("hash"):
                current_hash = hashlib.sha256(full_file_path.read_bytes()).hexdigest()[:16]
                if current_hash != latest["hash"]:
                    stale = True

            print(f"File: {file_path}")
            print(f"  {latest.get('one_liner', '(no description)')}")
            if stale:
                print("  [STALE] File has changed since this description was written.")
            print(f"  Source: {latest.get('source', 'unknown')}")
            print(f"  Updated: {latest.get('updatedAt', 'unknown')}")
        else:
            print(f"No description found for: {file_path}")

def cmd_task(args):
    """Run local task grill/plan/gate/validate/feedback workflow through smart_task."""
    result, should_fail = execute_task_command(args)
    if should_fail:
        print(json.dumps(result, indent=2, ensure_ascii=False))
        sys.exit(2)

    return result

def cmd_task_status(args):
    """Show project-local resumable task state."""
    return execute_task_status(args)

def cmd_usage_record(args):
    """Record one normalized task usage event."""
    return execute_usage_record(args)

def cmd_usage_report(args):
    """Render task efficiency evidence."""
    return execute_usage_report(args)

def cmd_tools(args):
    """Output structured JSON describing all available CLI commands and their arguments."""

    commands = [
        {
            "name": "init",
            "summary": "Initialize Flyto2 metadata and generated-index ignore rules in a project",
            "args": [
                {"name": "path", "type": "string", "required": False, "default": ".", "description": "Project root path"},
                {"name": "--name", "type": "string", "required": False, "description": "Project name (default: directory name)"},
                {"name": "--no-gitignore", "type": "boolean", "required": False, "default": False, "description": "Do not add .flyto/ and .flyto-index/ to .gitignore"},
                {"name": "--index", "type": "boolean", "required": False, "default": False, "description": "Run indexing immediately after init"},
            ],
            "outputs": [".flyto/flyto.json", ".flyto/nav/map.json", ".flyto/descriptions.jsonl", ".flyto/index/summary.json", ".flyto-index/index.json when --index is used"],
            "side_effects": ["creates .flyto/ directory", "may create .flyto-index/ when --index is used", "may modify .gitignore"],
            "examples": ["flyto-index init", "flyto-index init ./my-project --name myapp --index"],
            "exit_codes": {"0": "success", "1": "error"},
        },
        {
            "name": "scan",
            "summary": "Scan a project and build/update the code index",
            "args": [
                {"name": "path", "type": "string", "required": True, "description": "Project root path"},
                {"name": "--full", "type": "boolean", "required": False, "default": False, "description": "Full rebuild (not incremental)"},
                {"name": "--name", "type": "string", "required": False, "description": "Project name (default: directory name)"},
                {"name": "--output", "type": "string", "required": False, "description": "Index output directory"},
            ],
            "outputs": [".flyto-index/index.json", ".flyto-index/content.jsonl", ".flyto-index/bm25.json", ".flyto-index/semantic.json"],
            "side_effects": ["writes index files to .flyto-index/"],
            "examples": ["flyto-index scan .", "flyto-index scan ./my-project --full --name myapp"],
            "exit_codes": {"0": "success", "1": "error"},
        },
        {
            "name": "status",
            "summary": "Show .flyto-index/ status: file count, symbol count, dependency count, staleness",
            "args": [
                {"name": "path", "type": "string", "required": False, "default": ".", "description": "Project root path"},
                {"name": "--json", "type": "boolean", "required": False, "default": False, "description": "Output as JSON"},
            ],
            "outputs": [],
            "side_effects": [],
            "examples": ["flyto-index status", "flyto-index status ./my-project --json"],
            "exit_codes": {"0": "success", "1": "no .flyto-index/ or .flyto/ found"},
        },
        {
            "name": "impact",
            "summary": "Analyze what would be affected by changing a symbol",
            "args": [
                {"name": "symbol_id", "type": "string", "required": True, "description": "Symbol ID (format: project:path:type:name)"},
                {"name": "--path", "type": "string", "required": True, "description": "Project root path"},
                {"name": "--depth", "type": "integer", "required": False, "default": 3, "description": "Max analysis depth"},
            ],
            "outputs": [],
            "side_effects": [],
            "examples": ["flyto-index impact useAuth --path ."],
            "exit_codes": {"0": "success", "1": "symbol not found"},
        },
        {
            "name": "task",
            "summary": "Run local grill, plan, gate, validate, or feedback workflow with the latest source",
            "args": [
                {"name": "action", "type": "string", "required": True, "description": "grill, plan, gate, validate, or feedback"},
                {"name": "--description", "type": "string", "required": False, "description": "Task description for grill start or plan"},
                {"name": "--target", "type": "string[]", "required": False, "description": "Target file or symbol. Repeatable"},
                {"name": "--targets", "type": "string[]", "required": False, "description": "Comma-separated target files or symbols"},
                {"name": "--intent", "type": "string", "required": False, "default": "refactor", "description": "refactor, bugfix, feature, cleanup, or migration"},
                {"name": "--project", "type": "string", "required": False, "description": "Project name for scoped analysis"},
                {"name": "--task-contract", "type": "json|string", "required": False, "description": "Gate contract JSON object or JSON file path"},
                {"name": "--current-state", "type": "json|string", "required": False, "description": "Gate state JSON object or JSON file path"},
                {"name": "--next-phase", "type": "string", "required": False, "description": "Gate phase to enter"},
                {"name": "--test-path", "type": "string", "required": False, "description": "Test path for validate"},
                {"name": "--no-tests", "type": "boolean", "required": False, "default": False, "description": "Skip pytest during validate"},
                {"name": "--grill-action", "type": "string", "required": False, "default": "start", "description": "start, answer, status, freeze, or discard"},
                {"name": "--grill-session-id", "type": "string", "required": False, "description": "Session to resume or attach to plan"},
                {"name": "--decisions", "type": "json[]|string", "required": False, "description": "Decision array or JSON file path"},
                {"name": "--decision-id", "type": "string", "required": False, "description": "Frontier decision to answer"},
                {"name": "--answer", "type": "string", "required": False, "description": "Decision answer in any language"},
                {"name": "--selected-option", "type": "string", "required": False, "description": "Stable option ID"},
                {"name": "--accept-recommendation", "type": "boolean", "required": False, "default": False, "description": "Accept recommended answer"},
                {"name": "--mode", "type": "string", "required": False, "default": "interactive", "description": "interactive or batch"},
                {"name": "--locale", "type": "string", "required": False, "default": "und", "description": "BCP-47 metadata"},
                {"name": "--max-questions", "type": "integer", "required": False, "default": 8, "description": "Batch/frontier cap (1-20)"},
                {"name": "--request-id", "type": "string", "required": False, "description": "State-change idempotency key"},
                {"name": "--proof-receipts", "type": "json[]|string", "required": False, "description": "External proof receipt array or JSON file path"},
                {"name": "--require-proof", "type": "string[]", "required": False, "description": "Required external proof kind. Repeatable"},
                {"name": "--feedback-action", "type": "string", "required": False, "default": "record", "description": "record, summary, or resolve"},
                {"name": "--feedback-category", "type": "string", "required": False, "default": "other", "description": "Structured problem category"},
                {"name": "--feedback-summary", "type": "string", "required": False, "description": "Bounded problem note without source code"},
                {"name": "--feedback-severity", "type": "string", "required": False, "default": "medium", "description": "low, medium, high, or critical"},
                {"name": "--feedback-tool", "type": "string", "required": False, "description": "Tool or workflow that exposed the problem"},
                {"name": "--finding-id", "type": "string", "required": False, "description": "Stable finding identity"},
                {"name": "--rule-id", "type": "string", "required": False, "description": "Scanner or policy rule"},
                {"name": "--framework", "type": "string", "required": False, "description": "Relevant framework"},
                {"name": "--duration-ms", "type": "number", "required": False, "description": "Observed latency"},
                {"name": "--expected", "type": "string", "required": False, "description": "Expected behavior"},
                {"name": "--actual", "type": "string", "required": False, "description": "Observed behavior"},
                {"name": "--feedback-id", "type": "string", "required": False, "description": "Feedback group to resolve"},
                {"name": "--resolution", "type": "string", "required": False, "description": "Resolution note"},
                {"name": "--resolved-by", "type": "string", "required": False, "description": "Resolution owner"},
                {"name": "--since-days", "type": "integer", "required": False, "default": 90, "description": "Feedback summary lookback"},
                {"name": "--limit", "type": "integer", "required": False, "default": 10, "description": "Maximum feedback candidates"},
            ],
            "outputs": [],
            "side_effects": ["validate may run ruff and pytest"],
            "examples": [
                "flyto-index task grill --grill-action start --description 'add robot adapter' --decisions decisions.json",
                "flyto-index task grill --grill-action answer --grill-session-id grill_... --decision-id scope --accept-recommendation",
                "flyto-index task grill --grill-action freeze --grill-session-id grill_...",
                "flyto-index task plan --project flyto-engine --description 'split worker' --target cmd/worker/main.go",
                "flyto-index task gate --next-phase apply_changes --task-contract contract.json --current-state state.json",
                "flyto-index task validate --project flyto-indexer --test-path tests/test_cli_commands.py",
                "flyto-index task feedback --project flyto-indexer --feedback-category false_positive --feedback-summary 'Demo credential was classified as a real secret'",
                "flyto-index task feedback --project flyto-indexer --feedback-action summary",
            ],
            "exit_codes": {"0": "success", "2": "gate denied, validation failed, or task error"},
        },
        *task_evidence_tool_descriptions(),
        {
            "name": "context",
            "summary": "Get AI-ready context for a project (symbols, files, summaries)",
            "args": [
                {"name": "--path", "type": "string", "required": True, "description": "Project root path"},
                {"name": "--query", "type": "string", "required": False, "description": "Natural language query to focus context"},
                {"name": "--files", "type": "string[]", "required": False, "description": "Specific files to include"},
                {"name": "--symbols", "type": "string[]", "required": False, "description": "Specific symbols to include"},
                {"name": "--level", "type": "string", "required": False, "default": "auto", "description": "Detail level: l0 (outline), l1 (file), l2 (symbol), auto"},
            ],
            "outputs": [],
            "side_effects": [],
            "examples": ["flyto-index context --path . --query 'authentication flow'"],
            "exit_codes": {"0": "success", "1": "error"},
        },
        {
            "name": "verify",
            "summary": "Run no-dependency closed-loop verification for AI-assisted changes",
            "args": [
                {"name": "path", "type": "string", "required": False, "default": ".", "description": "Project root path"},
                {"name": "--full-scan", "type": "boolean", "required": False, "default": False, "description": "Rebuild the index before verification"},
                {"name": "--query", "type": "string", "required": False, "description": "Context query to verify"},
                {"name": "--symbol", "type": "string", "required": False, "description": "Symbol to verify with impact analysis"},
                {"name": "--strict", "type": "boolean", "required": False, "default": False, "description": "Treat warnings as failures"},
                {"name": "--baseline", "type": "string", "required": False, "description": "Baseline JSON result for regression gating"},
                {"name": "--regression-only", "type": "boolean", "required": False, "default": False, "description": "Only fail on checks that regress versus --baseline"},
                {"name": "--save-baseline", "type": "string", "required": False, "description": "Write current verification result to this JSON file"},
                {"name": "--policy", "type": "string", "required": False, "description": "Verify policy file (.flyto-rules.yaml/.json)"},
                {"name": "--report", "type": "string", "required": False, "description": "Write report artifact to this path"},
                {"name": "--report-format", "type": "string", "required": False, "default": "json", "description": "Report format: json, markdown, junit, sarif"},
                {"name": "--json", "type": "boolean", "required": False, "default": False, "description": "Output as JSON"},
            ],
            "outputs": [],
            "side_effects": ["may write .flyto-index/ when --full-scan is used or no index exists"],
            "examples": [
                "flyto-index verify .",
                "flyto-index verify . --full-scan --strict --json",
                "flyto-index verify . --baseline .flyto-baselines/current.json --regression-only",
            ],
            "exit_codes": {"0": "success", "2": "verification failed"},
        },
        {
            "name": "verify-workspace",
            "summary": "Run closed-loop verification across multiple projects",
            "args": [
                {"name": "path", "type": "string", "required": False, "default": ".", "description": "Workspace root path"},
                {"name": "--project", "type": "string[]", "required": False, "description": "Project path to verify. Repeatable. Defaults to auto-discovery"},
                {"name": "--full-scan", "type": "boolean", "required": False, "default": False, "description": "Rebuild each project index before verification"},
                {"name": "--strict", "type": "boolean", "required": False, "default": False, "description": "Treat warnings as failures"},
                {"name": "--baseline-dir", "type": "string", "required": False, "description": "Directory with <project>.json baseline files"},
                {"name": "--regression-only", "type": "boolean", "required": False, "default": False, "description": "Only fail projects that regress versus --baseline-dir"},
                {"name": "--changed-only", "type": "boolean", "required": False, "default": False, "description": "Only verify projects with git changes"},
                {"name": "--base", "type": "string", "required": False, "description": "Git base ref for --changed-only"},
                {"name": "--policy", "type": "string", "required": False, "description": "Shared verify policy file"},
                {"name": "--report", "type": "string", "required": False, "description": "Write report artifact to this path"},
                {"name": "--report-format", "type": "string", "required": False, "default": "json", "description": "Report format: json, markdown, junit, sarif"},
                {"name": "--json", "type": "boolean", "required": False, "default": False, "description": "Output as JSON"},
            ],
            "outputs": [],
            "side_effects": ["may write .flyto-index/ for each project when --full-scan is used or no index exists"],
            "examples": [
                "flyto-index verify-workspace /Users/chester/flytohub --project flyto-code --project flyto-engine",
                "flyto-index verify-workspace . --baseline-dir .flyto-baselines --regression-only --json",
            ],
            "exit_codes": {"0": "success", "2": "verification failed"},
        },
        {
            "name": "verify-baseline",
            "summary": "Create, compare, or update verify baseline JSON",
            "args": [
                {"name": "action", "type": "string", "required": True, "description": "create, compare, or update"},
                {"name": "path", "type": "string", "required": False, "default": ".", "description": "Project root path"},
                {"name": "--output-dir", "type": "string", "required": False, "default": ".flyto-baselines", "description": "Directory for <project>.json baseline files"},
                {"name": "--baseline", "type": "string", "required": False, "description": "Explicit baseline JSON path for compare"},
                {"name": "--full-scan", "type": "boolean", "required": False, "default": False, "description": "Rebuild the index before baseline action"},
                {"name": "--json", "type": "boolean", "required": False, "default": False, "description": "Output as JSON"},
            ],
            "outputs": [],
            "side_effects": ["create/update writes a baseline JSON file"],
            "examples": [
                "flyto-index verify-baseline create . --output-dir .flyto-baselines",
                "flyto-index verify-baseline compare . --baseline .flyto-baselines/flyto-indexer.json",
            ],
            "exit_codes": {"0": "success", "2": "regression detected"},
        },
        {
            "name": "outline",
            "summary": "Generate a project outline (L0 overview of structure and categories)",
            "args": [
                {"name": "path", "type": "string", "required": True, "description": "Project root path"},
                {"name": "--name", "type": "string", "required": False, "description": "Project name"},
            ],
            "outputs": [],
            "side_effects": [],
            "examples": ["flyto-index outline ."],
            "exit_codes": {"0": "success", "1": "error"},
        },
        {
            "name": "brief",
            "summary": "Generate a brief (<500 token) project summary from .flyto/ data",
            "args": [
                {"name": "path", "type": "string", "required": False, "default": ".", "description": "Project root path"},
            ],
            "outputs": [],
            "side_effects": [],
            "examples": ["flyto-index brief", "flyto-index brief ./my-project"],
            "exit_codes": {"0": "success", "1": "no .flyto/ found"},
        },
        {
            "name": "describe",
            "summary": "Read or write a one-liner semantic description for a file",
            "args": [
                {"name": "file_path", "type": "string", "required": True, "description": "File path relative to project root"},
                {"name": "--summary", "type": "string", "required": False, "description": "Description to write (omit to read existing)"},
                {"name": "--path", "type": "string", "required": False, "default": ".", "description": "Project root path"},
                {"name": "--source", "type": "string", "required": False, "default": "ai", "description": "Description source tag"},
            ],
            "outputs": [],
            "side_effects": ["appends to .flyto/descriptions.jsonl (write mode only)"],
            "examples": [
                "flyto-index describe src/api/auth.py",
                "flyto-index describe src/api/auth.py --summary 'User auth: login, register, JWT'",
            ],
            "exit_codes": {"0": "success", "1": "error"},
        },
        {
            "name": "tools",
            "summary": "List all available commands with arguments, examples, and side effects (this output)",
            "args": [
                {"name": "--json", "type": "boolean", "required": False, "default": True, "description": "Output as JSON (default)"},
                {"name": "--compact", "type": "boolean", "required": False, "default": False, "description": "Compact output (names and summaries only)"},
            ],
            "outputs": [],
            "side_effects": [],
            "examples": ["flyto-index tools", "flyto-index tools --compact"],
            "exit_codes": {"0": "success"},
        },
    ]

    now = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")

    if hasattr(args, "compact") and args.compact:
        return {
            "binary": "flyto-index",
            "generatedAt": now,
            "commands": [{"name": c["name"], "summary": c["summary"]} for c in commands],
        }

    return {
        "binary": "flyto-index",
        "version": __version__,
        "generatedAt": now,
        "usage": "flyto-index <command> [args]",
        "commands": commands,
    }

def cmd_install_hook(args):
    """Install or remove git post-commit hook for auto-reindexing."""
    project_path = Path(args.path).resolve()
    git_dir = project_path / ".git"

    if not git_dir.is_dir():
        print(f"Not a git repository: {project_path}", file=sys.stderr)
        sys.exit(1)

    hooks_dir = git_dir / "hooks"
    hooks_dir.mkdir(exist_ok=True)
    hook_file = hooks_dir / "post-commit"

    if args.remove:
        # Remove flyto lines between markers
        if not hook_file.exists():
            print("No post-commit hook found. Nothing to remove.")
            return None

        content = hook_file.read_text(encoding="utf-8")
        if HOOK_MARKER_BEGIN not in content:
            print("No flyto hook found in post-commit. Nothing to remove.")
            return None

        # Strip lines between markers (inclusive)
        lines = content.splitlines(keepends=True)
        new_lines = []
        inside_marker = False
        for line in lines:
            if HOOK_MARKER_BEGIN in line:
                inside_marker = True
                continue
            if HOOK_MARKER_END in line:
                inside_marker = False
                continue
            if not inside_marker:
                new_lines.append(line)

        new_content = "".join(new_lines).strip()
        # If only a shebang line remains, treat as empty
        if new_content and new_content.strip().replace("#!/bin/sh", "").strip():
            hook_file.write_text(new_content + "\n", encoding="utf-8")
        else:
            hook_file.unlink()

        print(f"Removed flyto hook from {hook_file}")
        return None

    # Install mode
    if hook_file.exists():
        content = hook_file.read_text(encoding="utf-8")
        if HOOK_MARKER_BEGIN in content:
            print("Flyto2 hook already installed. Skipping.")
            return None
        # Append to existing hook
        if not content.endswith("\n"):
            content += "\n"
        content += "\n" + HOOK_CONTENT
        hook_file.write_text(content, encoding="utf-8")
    else:
        hook_file.write_text("#!/bin/sh\n\n" + HOOK_CONTENT, encoding="utf-8")

    os.chmod(hook_file, 0o755)
    print(f"Installed flyto post-commit hook at {hook_file}")
    return None

def cmd_demo(args):
    """Quick 30-second value demo: scan + impact analysis."""
    from .engine import IndexEngine

    project_path = Path(args.path).resolve()
    project_name = project_path.name

    print(f"Scanning {project_path.name}...", end=" ", flush=True)
    t0 = time.monotonic()

    engine = IndexEngine(project_name, project_path)
    engine.scan(incremental=True)

    elapsed = time.monotonic() - t0
    symbol_count = len(engine.index.symbols)

    if symbol_count == 0:
        print("done")
        print()
        print("No symbols found. Make sure the project has supported source files")
        print("(.py, .ts, .tsx, .js, .jsx, .vue, .go, .rs, .java).")
        return None

    print(f"done ({symbol_count} symbols in {elapsed:.1f}s)")
    print()

    # Find symbol with highest reference_count
    best_symbol = max(
        engine.index.symbols.values(),
        key=lambda s: s.reference_count,
    )

    # Run impact analysis
    impact = engine.impact(best_symbol.id)
    chain = impact.get("impact_chain", [])

    # Collect affected files and total call sites
    total_affected = 0
    affected_files = set()
    for level in chain:
        for entry in level.get("affected", []):
            total_affected += 1
            affected_files.add(entry["path"])

    print(f"Example: What if you change `{best_symbol.name}`?")
    if total_affected > 0:
        file_word = "file" if len(affected_files) == 1 else "files"
        site_word = "call site" if total_affected == 1 else "call sites"
        print(f"  → {total_affected} {site_word} in {len(affected_files)} {file_word}")

        # Determine risk
        if total_affected >= 20:
            risk = "HIGH"
        elif total_affected >= 3:
            risk = "MEDIUM"
        else:
            risk = "LOW"
        print(f"  → Risk: {risk}")

        # Show affected files (max 5)
        shown = sorted(affected_files)[:5]
        print(f"  → Affected: {', '.join(shown)}")
        if len(affected_files) > 5:
            print(f"    ... and {len(affected_files) - 5} more")
    else:
        print("  → No other code depends on this symbol")

    print()
    print(f"Try: flyto-index impact {best_symbol.name} --path .")
    return None

def _configure_mcp_settings(remove=False):
    """Add or remove flyto-indexer from ~/.claude/settings.json."""
    settings_path = CLAUDE_SETTINGS_PATH

    if remove:
        if not settings_path.exists():
            return
        settings = json.loads(settings_path.read_text(encoding="utf-8"))
        servers = settings.get("mcpServers", {})
        if MCP_SERVER_KEY not in servers:
            return
        del servers[MCP_SERVER_KEY]
        settings_path.write_text(
            json.dumps(settings, indent=2, ensure_ascii=False) + "\n",
            encoding="utf-8",
        )
        print(f"  Removed {MCP_SERVER_KEY} from {settings_path}")
        return

    # Find python3 path
    python_path = sys.executable

    mcp_entry = {
        "command": python_path,
        "args": ["-m", "flyto_indexer.mcp_server"],
    }

    if settings_path.exists():
        settings = json.loads(settings_path.read_text(encoding="utf-8"))
    else:
        settings_path.parent.mkdir(parents=True, exist_ok=True)
        settings = {}

    servers = settings.setdefault("mcpServers", {})
    if MCP_SERVER_KEY in servers:
        existing = servers[MCP_SERVER_KEY]
        if existing.get("args") == mcp_entry["args"]:
            print(f"  MCP server already configured in {settings_path}")
            return
    servers[MCP_SERVER_KEY] = mcp_entry
    settings_path.write_text(
        json.dumps(settings, indent=2, ensure_ascii=False) + "\n",
        encoding="utf-8",
    )
    print(f"  MCP server configured in {settings_path}")

def cmd_setup(args):
    """One command setup: scan + CLAUDE.md + MCP config."""
    project_path = Path(args.path).resolve()

    if args.remove:
        print("Removing flyto-indexer setup...")
        # Remove CLAUDE.md section
        remove_args = argparse.Namespace(path=args.path, remove=True)
        cmd_setup_claude(remove_args)
        # Remove MCP settings
        _configure_mcp_settings(remove=True)
        print("\nDone. flyto-indexer removed.")
        return None

    print(f"Setting up flyto-indexer for {project_path.name}...\n")

    # Step 1: Scan
    index_dir = project_path / ".flyto-index"
    if index_dir.exists():
        print(f"  Index exists at {index_dir}, skipping scan.")
    else:
        print("  [1/3] Scanning project...")
        scan_args = argparse.Namespace(
            path=str(project_path), full=False,
            name=project_path.name, output=None,
        )
        cmd_scan(scan_args)

    # Step 2: CLAUDE.md
    print("  [2/3] Writing CLAUDE.md...")
    claude_args = argparse.Namespace(path=args.path, remove=False)
    cmd_setup_claude(claude_args)

    # Step 3: MCP settings
    print("  [3/3] Configuring MCP server...")
    _configure_mcp_settings()

    print("\nDone! Restart Claude Code to activate.")
    print("Try: ask Claude to audit this project.")
    return None

def cmd_setup_claude(args):
    """Add flyto-indexer instructions to CLAUDE.md."""
    project_path = Path(args.path).resolve()
    claude_md = project_path / "CLAUDE.md"

    if args.remove:
        if not claude_md.exists():
            print("No CLAUDE.md found. Nothing to remove.")
            return None
        content = claude_md.read_text(encoding="utf-8")
        if CLAUDE_MARKER_BEGIN not in content:
            print("No flyto-indexer section found in CLAUDE.md. Nothing to remove.")
            return None
        lines = content.splitlines(keepends=True)
        new_lines = []
        inside = False
        for line in lines:
            if CLAUDE_MARKER_BEGIN in line:
                inside = True
                continue
            if CLAUDE_MARKER_END in line:
                inside = False
                continue
            if not inside:
                new_lines.append(line)
        new_content = "".join(new_lines).strip()
        if new_content:
            claude_md.write_text(new_content + "\n", encoding="utf-8")
            print(f"Removed flyto-indexer section from {claude_md}")
        else:
            claude_md.unlink()
            print(f"CLAUDE.md was empty after removal — deleted {claude_md}")
        return None

    # Install mode
    if claude_md.exists():
        content = claude_md.read_text(encoding="utf-8")
        if CLAUDE_MARKER_BEGIN in content:
            print("flyto-indexer section already exists in CLAUDE.md. Skipping.")
            print("Use --remove to remove it first, then re-run.")
            return None
        if not content.endswith("\n"):
            content += "\n"
        content += "\n" + CLAUDE_SECTION
        claude_md.write_text(content, encoding="utf-8")
    else:
        claude_md.write_text(CLAUDE_SECTION, encoding="utf-8")

    print(f"Added flyto-indexer instructions to {claude_md}")
    print("AI assistants will now use analyze_task before modifying shared code.")
    return None

